---
apiVersion: v1
kind: Pod
metadata:
  name: nanokube
  namespace: kube-system
spec:
  containers:
    - name: controller-manager
      image: registry.k8s.io/kube-controller-manager:v1.35.0 # TODO(incomplete): version
      command: [kube-controller-manager]
      args:
        - --kubeconfig=/home/nanokube/.kube/config
        - --authentication-kubeconfig=/home/nanokube/.kube/config
        - --authorization-kubeconfig=/home/nanokube/.kube/config
        - --authentication-skip-lookup=true
        - --leader-elect=true
        - --controller-shutdown-timeout=0
        - --use-service-account-credentials=false
        - --tls-cert-file=/home/nanokube/certs/apiserver.crt
        - --tls-private-key-file=/home/nanokube/certs/apiserver.key
        - --service-account-private-key-file=/home/nanokube/certs/apiserver.key
      volumeMounts:
        - name: nanokube-home
          mountPath: /home/nanokube
    - name: scheduler
      image: registry.k8s.io/kube-scheduler:v1.35.0 # TODO(incomplete): version
      command: [kube-scheduler]
      args:
        - --kubeconfig=/home/nanokube/.kube/config
        - --authentication-kubeconfig=/home/nanokube/.kube/config
        - --authorization-kubeconfig=/home/nanokube/.kube/config
        - --authentication-skip-lookup=true
        - --leader-elect=true
        - --tls-cert-file=/home/nanokube/certs/apiserver.crt
        - --tls-private-key-file=/home/nanokube/certs/apiserver.key
      volumeMounts:
        - name: nanokube-home
          mountPath: /home/nanokube
  volumes:
    - name: home
      hostPath:
        path: "$HOME"
        type: Directory
    - name: nanokube-home
      hostPath:
        path: "$NANOKUBE_HOME"
        type: Directory
