---
apiVersion: v1
kind: Pod
metadata:
  name: nanokube
  # namespace: default
spec:
  containers:
    - name: cnuss-dev
      image: cnuss/dev:latest
      command:
        - busybox
        - httpd
        - -f
        - -p
        - "8080"
        - -h
        - /data
      ports:
        - containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      hostPath:
        path: "$NANOKUBE_DATA_DIR"
        type: Directory
