name: Build

on:
  push:
    branches: ["1.35"]
    paths-ignore:
      - .github/workflows/inspect.yaml
  pull_request:
    branches: ["1.35"]
    paths-ignore:
      - .github/workflows/inspect.yaml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-26
          - macos-26-intel
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1
      - uses: ./.github/actions/build
        with:
          runner: ${{ matrix.runner }}

  collect:
    outputs:
      artifacts: ${{ steps.collect.outputs.artifacts }}
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - id: collect
        uses: ./.github/actions/collect

  smoke:
    needs: collect
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - macos-26
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1

      - uses: ./.github/actions/test
        with:
          suite: smoke
          artifact: ${{ fromJSON(needs.collect.outputs.artifacts)[matrix.runner] }}
          log-name: nanokube-log-${{ matrix.runner }}-smoke

  release:
    needs: [collect, smoke]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: nanokube-*
          path: artifacts
          merge-multiple: true

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          allowUpdates: true
          removeArtifacts: true
          artifacts: artifacts/*
