name: Run Tests

on:
  push:
    branches: ["1.35"]
  pull_request:
    branches: ["1.35"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        runner:
          - ubuntu-latest
          - macos-26-intel
        suite:
          - e2e
          - critest
        runtime: [docker]
        rootless: [false]
        set-host: [true]
    steps:
      - name: Resolve env
        run: |
          echo "NANOKUBE_DATA=$HOME/.nanokube-${{ matrix.suite }}" >> "$GITHUB_ENV"
          echo "MATRIX_HASH=$(echo -n '${{ toJSON(matrix) }}' | sha256sum | cut -c1-8)" >> "$GITHUB_ENV"

      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - uses: docker/setup-docker-action@v5
        with:
          rootless: ${{ matrix.rootless }}
          set-host: ${{ matrix.set-host }}

      - name: Enable Lima port forwarding
        if: runner.os == 'macOS'
        run: |
          limactl stop docker-actions-toolkit
          yq -i '.portForwards += [{"guestIPMustBeZero": true, "hostIP": "0.0.0.0"}]' ~/.lima/docker-actions-toolkit/lima.yaml
          limactl start docker-actions-toolkit

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: actions/cache@v5
        with:
          path: ~/go/bin
          key: go-bin-${{ matrix.runner }}-${{ hashFiles('**/go.sum') }}

      - run: make init
      - run: make ${{ matrix.suite }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nanokube-log-${{ env.MATRIX_HASH }}
          path: ${{ env.NANOKUBE_DATA }}/log
